### ISSUE TITLE
Snap connections

### ISSUE THREAD

**Issue by raducostea** [Foblex/f-flow#40]
### Description

It will be a nice feature to have the ability to snap connections into place. Have some sort of threshold value and search for the closest `fNodeInput` to snap into.

**Comment by siarheihuzarevich** [comment]
Hello, could you please describe in more detail what you mean?

**Comment by raducostea** [comment]
Hello,

Sure. When you connect to nodes, you have to hover exactly over the fNodeInput and release to create the connections. What will be great that lets about 20px near the node, the "arrow" will snap and connect to the node. 

For example https://resources.jointjs.com/demos/rappid/apps/Chatbot/index.html

When you drag a connection, it snaps to a node if you are near it.

This will be useful when using small connection points.

**Comment by siarheihuzarevich** [comment]
@raducostea Thanks for the clarification. I think I can implement something like this in 2 - 3 weeks

**Comment by siarheihuzarevich** [comment]
@raducostea Done. [Snap connection documentation](https://flow.foblex.com/docs/f-snap-connection-component)
Also you can see the use of f-snap-connection in this example: [Foblex Flow DB Management Example](https://flow.foblex.com/docs/f-db-management-flow)

**Comment by raducostea** [comment]
> @raducostea Done. [Snap connection documentation](https://flow.foblex.com/docs/f-snap-connection-component) Also you can see the use of f-snap-connection in this example: [Foblex Flow DB Management Example](https://flow.foblex.com/docs/f-db-management-flow)

Nice!!! Appreciate it
