### ISSUE TITLE
Add the ability to export diagram to xml

### ISSUE THREAD

**Issue by hamletbarsamyan** [Foblex/f-flow#46]
### Description

Please add an endpoint to retrieve graph data as xml

**Comment by siarheihuzarevich** [comment]
@hamletbarsamyan 
I added a method to the FlowComponent called **getFlowState**. You can read more on [FFlowComponent Documentation](https://flow.foblex.com/docs/f-flow-component).

**Comment by hamletbarsamyan** [comment]
Thank you very much
