### ISSUE TITLE
Bug: After adding a Node, all the connections disappear.

### ISSUE THREAD

**Issue by pahlers** [Foblex/f-flow#51]
### Description

After adding a Node, all the connections disappear.
Tested with two browsers
Tested multiple examples

### Steps to Reproduce

1. Go to https://flow.foblex.com/docs/f-visual-programming-flow "Visual Programming Flow"
2. Add a Node
3. Connections will disappear
4. Switch to "DB Management" and back to "Visual Programming Flow"
5. Connection will be back.

### Expected Result

Connections stay visible

### Actual Result

Connections disappear.

### Environment Details

Firefox 130.0.1
Brave Version 1.69.168 Chromium: 128.0.6613.138 (Official Build) (64-bit)

### Screenshots or Videos

Example with Brave browser.
https://github.com/user-attachments/assets/1dc7a3ad-66a3-45e6-b6d6-e8c6d7ccef42

**Comment by pahlers** [comment]
That's fast! What was the bug?

Also other examples are broken like: 
- [ ] https://foblex.github.io/f-flow-example/
- [ ] https://foblex.github.io/f-scheme-editor/

**Comment by siarheihuzarevich** [comment]
@pahlers Error when merging from another branch

Examples: fixed

**Comment by pahlers** [comment]
Examples are working again. Thanks!

**Comment by siarheihuzarevich** [comment]
@pahlers Thank you for notifying us about the error, and if you have any questions or suggestions, please contact us. The documentation for the library does not cover even 50 percent of its functionality, so it can be difficult to understand
