### ISSUE TITLE
Cannot access 'AddPatternToBackgroundExecution' before initializatio

### ISSUE THREAD

**Issue by pauloegk** [Foblex/f-flow#53]
### Description

Hello, first of all, thank you for building this incredible library for Angular. We really needed something like this.

I'm facing problems here after the version upgrade.

I was using version 12.5.1 (everything was fine) and I upgraded to version 12.6.6
I'm using angular version 17.3.11

When I uploaded the application, I started to get this error here.

ERROR ReferenceError: Cannot access 'AddPatternToBackgroundExecution' before initialization
    at 36275 (foblex-flow.js:6790:5)

Can you help me?

**Comment by siarheihuzarevich** [comment]
@pauloegk Hello. Thank you. Fixed v16.0.0

**Comment by pauloegk** [comment]
@siarheihuzarevich thanks, When will version 16.0.0 be released?

**Comment by siarheihuzarevich** [comment]
@pauloegk it's already in release
