### ISSUE TITLE
On Clicking of any of the connection/Node fSelectionChange event should send the correct object data - help needed

### ISSUE THREAD

**Issue by anieshvishnu** [Foblex/f-flow#65]
![image](https://github.com/user-attachments/assets/00ee24b1-1e84-4556-acf1-0b20aa8dfddd)

fSelectionChange  event provides 'f-connection-3' how to identify which connects was clicked with that data

![image](https://github.com/user-attachments/assets/f3637200-cc53-4dfa-98df-8965fd55876a)

is there any way to get the selected connection object ?

**Comment by siarheihuzarevich** [comment]
f-connection-3 is the connection id. So you need to set it using the id attribute
<img width="916" alt="image" src="https://github.com/user-attachments/assets/299e15f2-131f-4d80-b3a8-5047c65f6ec8">
or it will be generated automatically
https://flow.foblex.com/docs/f-connection-component

**Comment by siarheihuzarevich** [comment]
![image](https://github.com/user-attachments/assets/da2d5def-e123-4c14-b5f3-ef1fcc13b35e)
