### ISSUE TITLE
Group items on drop

### ISSUE THREAD

**Issue by anderson-896** [Foblex/f-flow#71]
### Description

I'd like to have the option to drag an item over another and group them, also I'd like to have an event for when I drag an element over another in order to identify wich one is the target.

**Comment by siarheihuzarevich** [comment]
@anderson-896 I will add an event that triggers when a node is dragged over another node, detecting when the dragged node and cursor overlap with the target node. You will then be able to use this event for grouping, utilizing the grouping functionality on your end. I think I can do this within two weeks

**Comment by siarheihuzarevich** [comment]
@anderson-896 please let me know if this is what you need

**Comment by anderson-896** [comment]
> @anderson-896 please let me know if this is what you need

Yes, also would be interesting to have in this event:
both nodes: the group and the child dropped, the coordinates in the canva.

**Comment by siarheihuzarevich** [comment]
Hello. Sorry for the long wait. Here's your functionality [Drag to group](https://flow.foblex.com/examples/drag-to-group).
