### ISSUE TITLE
Dashed background pattern

### ISSUE THREAD

**Issue by anderson-896** [Foblex/f-flow#74]
### Description

I'd like to have the option for a dashed background pattern:
![image](https://github.com/user-attachments/assets/1a6779e6-bce9-40fc-b771-2883a97b3cbe)

**Comment by siarheihuzarevich** [comment]
@anderson-896 Hello, the documentation contains instructions on how to make a custom background pattern https://flow.foblex.com/docs/f-background-component

**Comment by anderson-896** [comment]
![image](https://github.com/user-attachments/assets/54198c43-d2bc-40ca-ac07-8ace7007cbda)
![image](https://github.com/user-attachments/assets/d89cf802-e18f-438c-8dec-13c82b5a201d)
The colors for the pattern doesn't apply properly.

**Comment by siarheihuzarevich** [comment]
Use hex colours please

**Comment by anderson-896** [comment]
Even with hex colours it doen't work

**Comment by siarheihuzarevich** [comment]
ah, yes, i see mistake, i will fix it on weekends. for now you can fix it using css


```
  .f-background {
    line {
      stroke: green;
    }
  } 
```

**Comment by siarheihuzarevich** [comment]
Also you can set line style to dashed using css

**Comment by anderson-896** [comment]
Yeah, It worked with stroke-dasharray, thanks.
