### ISSUE TITLE
Custom class on minimap nodes

### ISSUE THREAD

**Issue by anderson-896** [Foblex/f-flow#75]
### Description

I'd like to have custom classes on the nodes on minimap, so that I can apply different styles to them:
![image](https://github.com/user-attachments/assets/91f5fdd7-dd61-41b6-9af8-2c563487baab)

**Comment by siarheihuzarevich** [comment]
You mean different class for each node?

**Comment by anderson-896** [comment]
Yes

**Comment by anderson-896** [comment]
Since I have different type of nodes, and I would like to use different colors for them in the minimap
