### ISSUE TITLE
Bug: Browser crashes when there are several nodes

### ISSUE THREAD

**Issue by anderson-896** [Foblex/f-flow#76]
### Description

When displaying several nodes (e.g 500 nodes) the browser crashes

### Steps to Reproduce

Provide a ruge array of nodes (e.g 500 nodes) to the flow

### Expected Result

The nodes should show (virtual scroll?)

### Actual Result

The browser becomes slower and may crash

### Environment Details

Browser: 130.0.6723.70 (Official Build) (arm64)
Library Version: 16.0.5
Angular Version: 18.2.0

**Comment by siarheihuzarevich** [comment]
I will check it. Please provide screenshot and stacktrace.

**Comment by siarheihuzarevich** [comment]
@anderson-896 Not reproduced. I added 2500 nodes
