### ISSUE TITLE
Angular unit tests

### ISSUE THREAD

**Issue by MaiaLucas** [Foblex/f-flow#79]
### Description

Setup:
```
@angular/core: ^18.2.0
@foblex/flow: ^16.0.5
```
---
I create a component that use the foblex canvas but whenever I try to run the unit tests I get this error: 
` ReferenceError: Cannot access 'FExternalItemService' before initialization`

**Comment by anderson-896** [comment]
I am facing the same issue

**Comment by siarheihuzarevich** [comment]
Hello. What unit tests do you run?

**Comment by MaiaLucas** [comment]
Jest tests using testing-libraby

```

"@testing-library/angular": "17.3.1",
"@testing-library/jest-dom": "6.6.2",
"@testing-library/user-event": "14.5.2",

```

**Comment by siarheihuzarevich** [comment]
I don't have jest library in my project, never tested it. Only used karma

**Comment by siarheihuzarevich** [comment]
@anderson-896 I didn't say that, but it's possible. And from the description of the problem - that's the most I can answer

**Comment by MaiaLucas** [comment]
@siarheihuzarevich  Do you have any plans to add support for Angular 19? If so, when? Since they've moved the test library to jest, will you be adding compatibility with jest?
