### ISSUE TITLE
Add support for ports and connection validation for nodes

### ISSUE THREAD

**Issue by quentingllmt** [Foblex/f-flow#80]
### Description

Hello,

First of all, great work on this library!

Do you plan to add support for ports in the future? This would allow nodes to have multiple inputs and outputs.

Additionally, are you considering adding connection validations (e.g., preventing two inputs from being connected) or type checks, similar to what JointJS offers?
It is not in your f-scheme-editor example.

Illustration : 
<img width="220" alt="image" src="https://github.com/user-attachments/assets/0e310ad2-5aff-478e-b634-89901257b638">

Thanks for your great work and for considering this feature! 🙌

**Comment by siarheihuzarevich** [comment]
Hello. You can add many inputs and outputs inside a node. You can also manage connection validation yourself by checking it in the connectioncreate event

**Comment by anderson-896** [comment]
This feature already exists
