### ISSUE TITLE
Automatically Attach Node to Connection on Drop

### ISSUE THREAD

**Issue by SamkitSanghvi** [Foblex/f-flow#81]
### Description

When a node is dropped onto an existing connection between two nodes, it should automatically attach itself to the connection. This feature would enhance the user experience by simplifying node insertion into existing workflows.

Current Behavior:
- Nodes cannot be dropped directly onto a connection to attach themselves.

Expected Behavior:
-When a node is dragged and dropped onto a connection, the connection should split and attach to the dropped node, forming two new connections.

Example Use Case:
 Before :- Node A -----> Node B
 After dropping Node C on the connection(Wire) :- Node A -----> Node C -----> Node B

Thank you in advanced 🫡

**Comment by siarheihuzarevich** [comment]
https://flow.foblex.com/examples/assign-node-to-connection-on-drop
