### ISSUE TITLE
Bug: Connection Type Drawing problem

### ISSUE THREAD

**Issue by kyesil** [Foblex/f-flow#89]
### Description

Angular 19.0.5 kullanıyoruz connection-types örneğini yapmak istedik ancak bağlantilar doğru görünmüyor. Bence örnekteki common.scss kısmı  @foblex/flow paketinin içine eklenmeli bu şekilde daha karmaşık yapıyor.

### Steps to Reproduce

New project angular 19 & material
New angular application builder
Apply this example : https://flow.foblex.com/examples/connection-types

### Expected Result

![image](https://github.com/user-attachments/assets/8fddf346-78f9-4d1a-a72a-0942db8f13f2)

### Actual Result

![image](https://github.com/user-attachments/assets/6ef49a97-4ef1-4cd5-a145-1a8135cccc16)

### Environment Details

Angular CLI: 19.0.5
Node: 23.3.0 (Unsupported)
Package Manager: npm 10.9.2
OS: win32 x64

Angular: 19.0.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.5
@angular-devkit/build-angular   19.0.5
@angular-devkit/core            19.0.5
@angular-devkit/schematics      19.0.5
@angular/cdk                    19.0.3
@angular/cli                    19.0.5
@angular/material               19.0.3
@schematics/angular             19.0.5
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0

**Comment by siarheihuzarevich** [comment]
This is not a bug. Library doesn't have styles by default. You need to add them yourself.

**Comment by kyesil** [comment]
Ok. But what wrongs here:
https://stackblitz.com/edit/stackblitz-starters-euaf2ouu?file=src%2Fpages%2Fflowpage%2Fflowpage.component.ts

![image](https://github.com/user-attachments/assets/27457a1e-bbb4-44d4-bf85-aa1ada8d2d4e)

**Comment by bgreay** [comment]
@kyesil I had the same issue. It's to do with the app selector and how ::ng-deep works. 

In your component .ts file your selector is `app-flowpage` but in the .scss file you have `f-flow`

So change this:

```
::ng-deep f-flow {
  @include fcommon.connection;
}
```

to this:
```
::ng-deep app-flowpage {
  @include fcommon.connection;
}
```
