### ISSUE TITLE
Bug:  node selection and f-connetion type bezier

### ISSUE THREAD

**Issue by osmanHancer** [Foblex/f-flow#90]
### Description

-We are experiencing a bug with Foblex Flow on the [node selection example](https://flow.foblex.com/examples/node-selection). Specifically, even though we are using ChangeDetectionStrategy.OnPush, the detection mechanism does not seem to work as expected.

As a workaround, we are forced to manually create a ChangeDetectorRef instance and call cdr.detectChanges() to trigger the change detection. This behavior seems inconsistent and not aligned with how OnPush should work.

Could you please help us understand why this issue occurs and if there’s a proper solution?

-We are encountering another issue where the Bezier curve between nodes is not rendered correctly in Foblex Flow. Instead of a smooth curve, the connection lines appear as straight or incorrectly drawn paths. This affects the visual representation of node relationships.

Could you help us understand the root cause of this issue and provide a solution for ensuring proper Bezier curve rendering?

### Steps to Reproduce

Steps to Reproduce
Go to the Node Selection example on [Foblex Flow](https://flow.foblex.com/examples/node-selection).
Set ChangeDetectionStrategy.OnPush in the component.
Select or interact with a node to trigger change detection.
Observe that the change detection does not work as expected unless ChangeDetectorRef.detectChanges() is manually called.
For the Bezier curve issue:

Create a flow diagram with multiple nodes.
Attempt to connect the nodes using Bezier curves.
Observe that the connections are not rendered smoothly as Bezier curves but appear as straight or misaligned lines.

### Expected Result

Change Detection Issue:
When using ChangeDetectionStrategy.OnPush, the change detection mechanism should automatically trigger and update the view when a node selection or interaction occurs, without needing to manually call ChangeDetectorRef.detectChanges().

Bezier Curve Issue:
The connections between nodes should render smoothly as Bezier curves, providing a visually accurate and clean representation of relationships between nodes.

### Actual Result

Change Detection Issue:
Despite using ChangeDetectionStrategy.OnPush, the view does not update automatically when a node is selected or interacted with. To reflect the changes, we have to manually create a ChangeDetectorRef instance and call cdr.detectChanges().

Bezier Curve Issue:
The connections between nodes are not rendered as smooth Bezier curves. Instead, they appear as straight lines or incorrectly drawn paths, which disrupts the visual flow of the diagram.

### Environment Details

Angular Version: 19

### Screenshots or Videos

![WhatsApp Image 2024-12-16 at 11 27 57](https://github.com/user-attachments/assets/0a30102b-d1c3-457c-88fc-a9b19d617a13)

**Comment by siarheihuzarevich** [comment]
Let’s address both of your issues:

**1. ChangeDetectionStrategy.OnPush**

![image](https://github.com/user-attachments/assets/c346b8f5-b15f-46e5-b78d-2db936ae6333)


In the example provided in the documentation, ChangeDetectionStrategy.OnPush works as expected. If you’re experiencing issues, the likely cause is:
	•	Your component isn’t receiving a new object through @Input, or there’s a mutation of an existing object, which doesn’t trigger Angular’s change detection mechanism for OnPush. Remember, OnPush relies on detecting reference changes to trigger updates.
	•	Make sure you’re passing a new object or explicitly using markForCheck() if necessary.

Please check your code and confirm that:
	1.	A new object is passed as input to the component.
	2.	There are no mutations to the object being passed.

If this doesn’t resolve your issue, I recommend reviewing the example in the documentation, where OnPush is properly implemented.


**2. Bezier Curve Rendering**

The second issue is likely due to missing styles. In my documentation examples, I’ve included the necessary CSS styles to ensure that Bezier curves render correctly. Without these styles:
	•	Connections may render incorrectly or appear as straight lines.

Recommendations:
	**1.	Verify that the styles provided in the documentation are applied to your components.**
	2.	Ensure that the dimensions and positions of your nodes are correct, as these directly affect the calculation of the Bezier curves.



Please review these points carefully. The documentation examples are working as intended and should guide you to resolve your issues.

**Comment by osmanHancer** [comment]
https://github.com/[osmanHancer/foblex](https://github.com/osmanHancer/foblex)
here is my code please check it

**Comment by siarheihuzarevich** [comment]
![image](https://github.com/user-attachments/assets/3afcec90-b766-479d-a010-25678506ecb3)
![image](https://github.com/user-attachments/assets/ff3ba432-9586-4b4a-8250-bf537280c711)
![image](https://github.com/user-attachments/assets/f77a6f66-8b39-4991-a471-40ab2268b262)

**Comment by osmanHancer** [comment]
Bezier issue is resolved but changedetectionstrategy still does not work

**Comment by kyesil** [comment]
I think the common.scss part should be embedded  @foblex/flow package, this way it makes it more complex. 
look my example:
https://stackblitz.com/edit/stackblitz-starters-euaf2ouu?file=src%2Fpages%2Fflowpage%2Fflowpage.component.ts

**Comment by siarheihuzarevich** [comment]
> I think the common.scss part should be embedded  @foblex/flow package, this way it makes it more complex. 
> 
> look my example:
> 
> https://stackblitz.com/edit/stackblitz-starters-euaf2ouu?file=src%2Fpages%2Fflowpage%2Fflowpage.component.ts

You can fork it and add it to your version. Thanks

**Comment by kyesil** [comment]
But not working as  `::ng-deep app-flowpage {..`
![image](https://github.com/user-attachments/assets/a9123436-0efc-4851-b65d-4dda622c1f4b)

**Comment by siarheihuzarevich** [comment]
> Bezier issue is resolved but changedetectionstrategy still does not work

The library runs outside the zone, so its events do not trigger the change detection cycle. You must call them yourself if needed. This information is described on the documentation site.

if you want the event data to be displayed, you need to recreate the array and not push it into it.
